apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-api
  namespace: tacos-app
  labels:
    app: reservation-api
    tier: backend
    workload-type: general
    app.kubernetes.io/name: reservation-api
    app.kubernetes.io/part-of: traffic-tacos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-api
  template:
    metadata:
      labels:
        app: reservation-api
        tier: backend
        workload-type: general
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload-type
                operator: In
                values:
                - general
              - key: node-type
                operator: In
                values:
                - mix
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - reservation-api
              topologyKey: kubernetes.io/hostname
      
      tolerations:
      - key: karpenter.sh/capacity-type
        operator: Equal
        value: spot
        effect: NoSchedule
      - key: node.karpenter.sh/initializing
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: reservation-api
        image: 137406935518.dkr.ecr.ap-northeast-2.amazonaws.com/traffic-tacos-reservation-api:latest
        imagePullPolicy: Always
        
        ports:
        - name: http
          containerPort: 8010
          protocol: TCP
        - name: grpc
          containerPort: 8011
          protocol: TCP
        
        env:
        - name: SERVER_PORT
          value: "8010"
        - name: GRPC_PORT
          value: "8011"
        - name: REDIS_ADDRESS
          value: master.traffic-tacos-redis.w6eqga.apn2.cache.amazonaws.com:6379
        - name: REDIS_TLS_ENABLED
          value: "true"
        - name: REDIS_TLS_INSECURE_SKIP_VERIFY
          value: "true"
        - name: INVENTORY_GRPC_ADDR
          value: inventory-api:8020
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-collector.otel-collector:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"

        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8010
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8010
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3