apiVersion: v1
kind: Service
metadata:
  name: reservation-api
  namespace: tacos-app
  labels:
    app: reservation-api
    tier: backend
spec:
  type: NodePort
  selector:
    app: reservation-api
  ports:
  - name: http
    port: 8010
    targetPort: 8010
    nodePort: 30010
  - name: grpc
    port: 8011
    targetPort: 8011
    nodePort: 30011
