apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-aws-sigv4-proxy
spec:
  rules:
    - name: add-sigv4-sidecar
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - load-test
          selector:
            matchLabels:
              app: k6-operator
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - name: aws-sigv4-proxy
                image: public.ecr.aws/aws-observability/aws-sigv4-proxy:latest
                args:
                  - "--name=aps"
                  - "--region=ap-northeast-2"
                  - "--host=aps-workspaces.ap-northeast-2.amazonaws.com"
                  - "--port=:8005"
                volumeMounts:
                - name: aws-iam-token
                  mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                  readOnly: true
                ports:
                  - containerPort: 8005
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
