apiVersion: batch/v1
kind: Job
metadata:
  name: k6-loadtest-prod
  namespace: load-test
  labels:
    app: k6
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  parallelism: 3
  template:
    metadata:
      labels:
        app: k6
    spec:
      restartPolicy: Never
      serviceAccountName: k6-runner
      nodeSelector:
        workload-type: loadtest
      tolerations:
        - effect: NoSchedule
          key: workload
          operator: Equal
          value: loadtest
      volumes:
        - name: aws-iam-token
          projected:
            defaultMode: 420
            sources:
            - serviceAccountToken:
                audience: sts.amazonaws.com
                expirationSeconds: 86400
                path: token
        - name: k6-test-volume
          configMap:
            defaultMode: 420
            name: k6-cm-prod
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6"]
          args:
            - "run"
            - "/test/script.js"
          volumeMounts:
            - mountPath: /test
              name: k6-test-volume
              readOnly: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TEST_ID
              value: "k6-10k-20251009-002"
            - name: TARGET_BASE_URL
              value: "https://api.traffictacos.store"
            - name: K6_OUT
              value: experimental-prometheus-rw
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: http://localhost:8005/workspaces/ws-ec1155d6-1ea8-4822-b9e9-fdec9424dcb9/api/v1/remote_write
            - name: K6_PROMETHEUS_RW_TREND_STATS
              value: "p(90),p(95),p(99),max,min,avg,med"
            - name: K6_PROMETHEUS_RW_TAGS
              value: "testid,tags,scenario,method,status,expected_response,pod"
            - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
              value: "5s"
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
        - name: aws-sigv4-proxy
          image: public.ecr.aws/aws-observability/aws-sigv4-proxy:latest
          args:
            - "--name=aps"
            - "--region=ap-northeast-2"
            - "--host=aps-workspaces.ap-northeast-2.amazonaws.com"
            - "--port=:8005"
          volumeMounts:
          - name: aws-iam-token
            mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
            readOnly: true
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: "100m"
              memory: "20Mi"
            limits:
              cpu: "100m"
              memory: "30Mi"
