apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-worker
  namespace: tacos-app
  labels:
    app: reservation-worker
    tier: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-worker
  template:
    metadata:
      labels:
        app: reservation-worker
    spec:
      containers:
      - name: reservation-worker
        image: 137406935518.dkr.ecr.ap-northeast-2.amazonaws.com/traffic-tacos-reservation-worker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8040
        - containerPort: 8041
        env:
        - name: SERVER_PORT
          value: "8040"
        - name: GRPC_PORT
          value: "8041"
        - name: REDIS_ADDRESS
          value: redis:6379
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
