apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-worker
  namespace: tacos-app
  labels:
    app: reservation-worker
    tier: worker
    workload-type: general
    app.kubernetes.io/name: reservation-worker
    app.kubernetes.io/part-of: traffic-tacos
spec:
  replicas: 1  # KEDA will manage scaling
  selector:
    matchLabels:
      app: reservation-worker
  template:
    metadata:
      labels:
        app: reservation-worker
        tier: worker
        workload-type: general
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload-type
                operator: In
                values:
                - general
              - key: node-type
                operator: In
                values:
                - mix
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - reservation-worker
              topologyKey: kubernetes.io/hostname
      
      tolerations:
      - key: karpenter.sh/capacity-type
        operator: Equal
        value: spot
        effect: NoSchedule
      - key: node.karpenter.sh/initializing
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: reservation-worker
        image: 137406935518.dkr.ecr.ap-northeast-2.amazonaws.com/traffic-tacos-reservation-worker:latest
        imagePullPolicy: Always
        
        ports:
        - name: http
          containerPort: 8040
          protocol: TCP
        - name: grpc
          containerPort: 8041
          protocol: TCP
        
        env:
        - name: SERVER_PORT
          value: "8040"
        - name: GRPC_PORT
          value: "8041"
        - name: REDIS_ADDRESS
          value: master.traffic-tacos-redis.w6eqga.apn2.cache.amazonaws.com:6379
        
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8040
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8040
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3