apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: reservation-worker-scaler
  namespace: tacos-app
  labels:
    app: reservation-worker
spec:
  scaleTargetRef:
    name: reservation-worker
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
  - type: redis
    metadata:
      address: master.traffic-tacos-redis.w6eqga.apn2.cache.amazonaws.com:6379
      listName: reservation_queue
      listLength: "10"
      activationListLength: "5"
    authenticationRef:
      name: redis-auth-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-auth-trigger
  namespace: tacos-app
spec:
  secretTargetRef:
  - parameter: password
    name: redis-password
    key: password