apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: reservation-worker-scaler
  namespace: tacos-app
  labels:
    app: reservation-worker
spec:
  scaleTargetRef:
    name: reservation-worker
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.ap-northeast-2.amazonaws.com/137406935518/reservation-queue
      queueLength: "10"
      awsRegion: ap-northeast-2
      identityOwner: operator