apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reservation-worker-pdb
  namespace: tacos-app
  labels:
    app: reservation-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: reservation-worker
