apiVersion: v1
kind: Service
metadata:
  name: reservation-worker
  namespace: tacos-app
  labels:
    app: reservation-worker
    tier: worker
spec:
  type: ClusterIP
  selector:
    app: reservation-worker
  ports:
  - name: http
    port: 8040
    targetPort: 8040
  - name: grpc
    port: 8041
    targetPort: 8041
