apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    capacity-preference: spot
    node-type: mix
    workload-type: general
  name: mixed-workload
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: "100"
    memory: 250Gi
  template:
    metadata:
      labels:
        node-type: mix
        workload-type: general
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-nodeclass
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3a
        - t3
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - medium
        - large
        - xlarge
      startupTaints:
      - effect: NoSchedule
        key: node.karpenter.sh/initializing
        value: "true"

~             