apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: on-demand-critical
  labels:
    capacity-preference: on-demand
    node-type: on-demand
    workload-type: critical
spec:
  disruption:
    budgets:
    - nodes: 20%
    consolidateAfter: 2m      
    consolidationPolicy: WhenEmpty
  limits:
    cpu: "300"
    memory: 800Gi
  template:
    metadata:
      labels:
        node-type: on-demand
        workload-type: critical
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-nodeclass
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3a
        - t3
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - large     
        - xlarge   
        - 2xlarge

      # startupTaints:
      # - key: node.karpenter.sh/initializing
      #   value: "true"
      #   effect: NoSchedule

  ttlSecondsUntilExpired: 30       
  consolidation:
    enabled: true             
  weight: 50
