apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    capacity-preference: on-demand
    node-type: on-demand
    workload-type: critical
  name: on-demand-critical
spec:
  disruption:
    budgets:
    - nodes: 20%
    consolidateAfter: 5m
    consolidationPolicy: WhenEmpty
  limits:
    cpu: "300"
    memory: 800Gi
  template:
    metadata:
      labels:
        node-type: on-demand
        workload-type: critical
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-nodeclass
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - t3a
        - t3
        - m6i
        - m7i
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - medium
        - large
        - xlarge
      startupTaints:
      - effect: NoSchedule
        key: node.karpenter.sh/initializing
        value: "true"
  weight: 50
