apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-sim-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: payment-sim-api
    app.kubernetes.io/part-of: traffic-tacos
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: traffic-tacos
  
  source:
    repoURL: https://github.com/jmcunst/traffic-tacos-deployment
    targetRevision: main
    path: manifests/payment-sim-api
  
  destination:
    server: https://kubernetes.default.svc
    namespace: tacos-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
