# App of Apps Pattern
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: traffic-tacos
  source:
    repoURL: https://github.com/traffic-tacos/deployment-repo
    targetRevision: main
    path: applications/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
