apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script-for-test
  namespace: load-test
  labels:
    app.kubernetes.io/name: load-test-cm
    app.kubernetes.io/component: load-test
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
      stages: [
        { duration: '30s', target: 20 },
        { duration: '1m30s', target: 10 },
        { duration: '20s', target: 0 },
      ],
    };

    export default function () {
      http.get('https://quickpizza.grafana.com');
      sleep(1);
    }