apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: test-1
  namespace: load-test
  labels:
    app.kubernetes.io/name: load-test-testrun
    app.kubernetes.io/component: load-test
spec:
  parallelism: 3
  separate: true
  script:
    configMap:
      name: k6-script-for-test
      file: script.js
  arguments: "-o experimental-prometheus-rw --tag testid=test-1"
  runner:
    nodeSelector:
      workload-type: loadtest
    tolerations:
      - key: "workload"
        operator: "Equal"
        value: "loadtest"
        effect: "NoSchedule"
    image: grafana/k6:0.51.0
    serviceAccountName: k6-runner
    env:
      - name: TARGET_BASE_URL
        value: "https://quickpizza.grafana.com"
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-ec1155d6-1ea8-4822-b9e9-fdec9424dcb9/api/v1/remote_write"
      - name: K6_PROMETHEUS_RW_TREND_STATS
        value: "p(90),p(95),p(99),max"
      - name: K6_PROMETHEUS_RW_STALE_MARKERS
        value: "true"
      # K6_PROMETHEUS_RW_SIGV4_REGION 관련 변수 설정 X