apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    architecture: amd64
    instance-family: t3a-preferred
  name: default-nodeclass
spec:
  amiFamily: AL2023
  amiSelectorTerms:
  - id: ami-041625eac95e30c1c  # v1.33.4 (Working AMI) - v1.33.5 has node registration issues
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      encrypted: true
      volumeSize: 30Gi
      volumeType: gp3
  instanceStorePolicy: RAID0
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  role: ticket-cluster-eks-worker-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ticket-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ticket-cluster
  tags:
    Cluster: ticket-cluster
    ManagedBy: karpenter
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh ticket-cluster

    systemctl enable amazon-ssm-agent
    systemctl start amazon-ssm-agent
