apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: tacos-app
  labels:
    app: inventory-api
    tier: backend
    workload-type: general
    app.kubernetes.io/name: inventory-api
    app.kubernetes.io/part-of: traffic-tacos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
        tier: backend
        workload-type: general
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload-type
                operator: In
                values:
                - general
              - key: node-type
                operator: In
                values:
                - mix
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - inventory-api
              topologyKey: kubernetes.io/hostname
      
      tolerations:
      - key: karpenter.sh/capacity-type
        operator: Equal
        value: spot
        effect: NoSchedule
      - key: node.karpenter.sh/initializing
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: inventory-api
        image: 137406935518.dkr.ecr.ap-northeast-2.amazonaws.com/traffic-tacos-inventory-api:c448e3b
        imagePullPolicy: Always
        
        ports:
        - name: grpc
          containerPort: 8020
          protocol: TCP
        
        env:
        - name: GRPC_PORT
          value: "8020"
        
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        
        livenessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
