apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: tacos-app
  labels:
    app: inventory-api
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api
        image: 137406935518.dkr.ecr.ap-northeast-2.amazonaws.com/traffic-tacos-inventory-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
        - containerPort: 8021
        env:
        - name: SERVER_PORT
          value: "8020"
        - name: GRPC_PORT
          value: "8021"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
