apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  namespace: tacos-app
  labels:
    app: inventory-api
    tier: backend
spec:
  type: NodePort
  selector:
    app: inventory-api
  ports:
  - name: http
    port: 8020
    targetPort: 8020
    nodePort: 30020
  - name: grpc
    port: 8021
    targetPort: 8021
    nodePort: 30021
