apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-traffictacos-route
  namespace: tacos-app
spec:
  parentRefs:
    - name: api-traffictacos-gateway
      namespace: gateway
      sectionName: https 
    - name: api-traffictacos-gateway
      namespace: gateway
      sectionName: http   
  hostnames:
    - "api.traffictacos.store"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1
      backendRefs:
        - name: gateway-api
          port: 8000
          weight: 100
    - matches:
        - path:
            type: Exact
            value: /healthz
      backendRefs:
        - name: gateway-api
          port: 8000
    - matches:
        - path:
            type: Exact
            value: /readyz
      backendRefs:
        - name: gateway-api
          port: 8000
    - matches:
        - path:
            type: Exact
            value: /metrics
      backendRefs:
        - name: gateway-api
          port: 8000
    - matches:
        - path:
            type: PathPrefix
            value: /swagger
      backendRefs:
        - name: gateway-api
          port: 8000