apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-api-pdb
  namespace: tacos-app
  labels:
    app: gateway-api
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: gateway-api
