name: Deploy k6, k6-operator, kube-prometheus-stack on EKS

on:
  workflow_dispatch: {}
  push:
    branches: [ main, cicd ]
    paths:
      - "k6/**"
      - "kube-prometheus-stack/**"
      - ".github/workflows/stress-test.yml"

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        uses: aws-actions/eks-kubectl@v1
        with:
          cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          region: ${{ env.AWS_REGION }}

      - name: Create namespaces
        run: |
          kubectl apply -f common\namespaces/monitoring-ns.yaml

      - name: Add Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
      - name: Install/Upgrade kube-prometheus-stack
        run: |
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            -n monitoring \
            -f infra-k6/kps/values.yaml

      - name: Install/Upgrade k6-operator
        run: |
          curl -s https://raw.githubusercontent.com/grafana/k6-operator/main/bundle.yaml | kubectl apply -f -

      - name: Create/Update k6 script ConfigMap
        run: |
          kubectl -n perf create configmap k6-script --from-file=script.js=k6/k6-scripts/script-template.js --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply k6 TestRun
        run: kubectl apply -f k6/TestRun.yaml

      - name: Check pods
        run: |
          kubectl -n monitoring get pods
